[package]
name = "wsrs"
version = "0.1.0"
edition = "2021"

[dependencies]
tracing = "0.1.41"
tracing-subscriber = "0.3.19"
tungstenite = "0.26.1"
uuid = { version = "1.11.0", features = ["v4"] }

[profile.release]
debug = 1
